# Generated by Django 5.1.6 on 2025-03-05 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='students',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order_Course',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
